# Generated by Django 4.1.2 on 2022-10-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
