# Generated by Django 4.1.2 on 2022-11-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cargo_cargo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCargo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('description', models.CharField(max_length=255)),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargo')),
            ],
            bases=('home.basemodel',),
        ),
    ]
