# Generated by Django 4.1.2 on 2022-11-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trackcargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
