# Generated by Django 4.1.2 on 2022-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vehiclecategory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
