# Generated by Django 4.1.2 on 2022-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_currentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='lon',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
